import Link from "next/link";

export const metadata = { title: "Terms of Service – YT-brief" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black text-white font-sans">
      <div className="max-w-3xl mx-auto px-6 py-20">
        <Link href="/" className="text-sky-500 text-sm font-bold hover:text-sky-400 transition-colors">
          ← Back to YT-brief
        </Link>

        <h1 className="mt-8 text-4xl font-extrabold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-zinc-500 text-sm mb-12">Last updated: May 14, 2026</p>

        <div className="space-y-10 text-zinc-300 leading-relaxed">
          <section>
            <h2 className="text-white font-bold text-xl mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using YT-brief (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-bold text-xl mb-3">2. Description of Service</h2>
            <p>YT-brief provides automated video summarization based on publicly available captions from YouTube videos. Summaries are generated by our analysis engine and are provided for informational purposes only.</p>
          </section>

          <section>
            <h2 className="text-white font-bold text-xl mb-3">3. Accuracy Disclaimer</h2>
            <p>Summaries are provided &ldquo;as-is&rdquo; and may not be 100% accurate, complete, or up to date. YT-brief makes no warranties regarding the accuracy, reliability, or fitness of the summaries for any particular purpose. You are solely responsible for how you use the information provided.</p>
          </section>

          <section>
            <h2 className="text-white font-bold text-xl mb-3">4. Caption Availability</h2>
            <p>The Service depends on captions being available for the requested video. YT-brief does not guarantee that summaries can be generated for every video. No refund or credit will be issued for videos that cannot be processed due to missing or unavailable captions.</p>
          </section>

          <section>
            <h2 className="text-white font-bold text-xl mb-3">5. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-zinc-400">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on the intellectual property rights of others</li>
              <li>Attempt to reverse engineer, scrape, or abuse the Service</li>
              <li>Resell or redistribute summaries for commercial purposes without permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-white font-bold text-xl mb-3">6. Subscriptions and Billing</h2>
            <p>Paid plans are billed monthly. Your subscription will automatically renew each month unless cancelled. You may cancel at any time through your account settings. Cancellation takes effect at the end of the current billing period. Please refer to our <Link href="/refund" className="text-sky-400 hover:underline">Refund Policy</Link> for details on refunds.</p>
          </section>

          <section>
            <h2 className="text-white font-bold text-xl mb-3">7. Service Availability</h2>
            <p>We reserve the right to modify, suspend, or discontinue the Service at any time, with or without notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuation of the Service.</p>
          </section>

          <section>
            <h2 className="text-white font-bold text-xl mb-3">8. Limitation of Liability</h2>
            <p>To the fullest extent permitted by law, YT-brief shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability to you shall not exceed the amount you paid us in the three months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-white font-bold text-xl mb-3">9. Changes to Terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the new Terms. We will notify users of significant changes via email or an in-app notice.</p>
          </section>

          <section>
            <h2 className="text-white font-bold text-xl mb-3">10. Contact</h2>
            <p>For any questions regarding these Terms, please contact us at <span className="text-sky-400">support@yt-brief.com</span>.</p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-white/10 flex gap-6 text-xs text-zinc-600">
          <Link href="/privacy" className="hover:text-zinc-400 transition-colors">Privacy Policy</Link>
          <Link href="/refund" className="hover:text-zinc-400 transition-colors">Refund Policy</Link>
          <Link href="/" className="hover:text-zinc-400 transition-colors">Home</Link>
        </div>
      </div>
    </div>
  );
}
